server:
  port: 9000

spring:
  datasource:
    url: jdbc:mariadb://albaayo.c0fevms7runj.us-east-2.rds.amazonaws.com:3306/albaayo
    username: seonje
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 595511307863-6abtdm5092jocvgns0bl1jtsafnu4pk1.apps.googleusercontent.com
#            client-secret: 6rRrABg3GifKSt8nEm5Q2l1B
#            scope:
#              - email
#              - profile
#          naver:
#            client-id: T7PkGsLoMsNQOwO5lzK7
#            client-secret: iMMZwJXPUD
#            scope:
#              - email
#              - name
#              - profile_image
#            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
#            authorization-grant-type: authorization_code
#            client-name: Naver
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
#
#  session:
#    store-type: jdbc
#    jdbc:
#      initialize-schema: always
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/albaayo
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
loggin:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400



